<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="admin-PC" name="cases.UCLoginTest" tests="3" failures="2" timestamp="25 Jun 2014 12:42:05 GMT" time="10.290" errors="0">
  <testcase name="InputNullPwdTest" time="1.106" classname="cases.UCLoginTest"/>
  <testcase name="InputRightPwdTest" time="6.517" classname="cases.UCLoginTest">
    <failure type="java.lang.Exception" message="[失败]assertTrue操作异常：
Expected: is &lt;true&gt;
     got: &lt;false&gt;
,实际值:false,期望值:true">
      <![CDATA[java.lang.Exception: [失败]assertTrue操作异常：
Expected: is <true>
     got: <false>
,实际值:false,期望值:true
	at com.zendaimoney.Dokodemo.logger.LogUtils.setAssertFailed(LogUtils.java:382)
	at com.zendaimoney.Dokodemo.DokodemoTool.assertTrue(DokodemoTool.java:69)
	at com.zendaimoney.Dokodemo.ETestWebUIBaseCase.assertTrue(ETestWebUIBaseCase.java:44)
	at cases.UCLoginTest.InputRightPwdTest(UCLoginTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- InputRightPwdTest -->
  <testcase name="InputWrongPwdTest" time="2.667" classname="cases.UCLoginTest">
    <failure type="java.lang.Exception" message="[失败]assertTrue操作异常：
Expected: is &lt;true&gt;
     got: &lt;false&gt;
,实际值:false,期望值:true">
      <![CDATA[java.lang.Exception: [失败]assertTrue操作异常：
Expected: is <true>
     got: <false>
,实际值:false,期望值:true
	at com.zendaimoney.Dokodemo.logger.LogUtils.setAssertFailed(LogUtils.java:382)
	at com.zendaimoney.Dokodemo.DokodemoTool.assertTrue(DokodemoTool.java:69)
	at com.zendaimoney.Dokodemo.ETestWebUIBaseCase.assertTrue(ETestWebUIBaseCase.java:44)
	at cases.UCLoginTest.InputWrongPwdTest(UCLoginTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- InputWrongPwdTest -->
</testsuite> <!-- cases.UCLoginTest -->
